name: movies_flutter
description: Trabalho para conclusão da matéria APLICAÇÕES NATIVAS CROSS-PLATFORM COM FLUTTER.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  url_launcher: ^6.1.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  http: ^0.13.4
  intl: ^0.17.0
  transparent_image: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  faker: ^2.0.0
  mocktail: ^0.3.0
  network_image_mock: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true


