// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2tS6L1vn45z3Ow3pEtU_PBnbNnBEclM',
    appId: '1:702815321617:android:d09fedd6a7a7fe4c4a7bb0',
    messagingSenderId: '702815321617',
    projectId: 'davis-fiap',
    storageBucket: 'davis-fiap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP8hSm6LfB8h8iHUf9oCD38R_7sTikAfA',
    appId: '1:702815321617:ios:9d552643d5bff8754a7bb0',
    messagingSenderId: '702815321617',
    projectId: 'davis-fiap',
    storageBucket: 'davis-fiap.appspot.com',
    iosClientId: '702815321617-ch5kkmef46hdvlvjjo2pjk3mqgf0pu2t.apps.googleusercontent.com',
    iosBundleId: 'com.mba.davis.mbaDavis',
  );
}
